### ISSUE TITLE
和原作者的代码实现略有不同

### ISSUE THREAD

**Issue by Atakey** [qq547276542/TF_adapting_transformer#2]
https://github.com/qq547276542/TF_adapting_transformer/blob/8c28f22f5cd4e81b29e1cbad02257aa96cca7bf3/relative_transformer_module.py#L82
对比原作者torch的实现，此处略有不同，请问这么实现是基于什么考虑呢？另外，原作者此处的代码自己也没怎么理解透  :)

**Comment by qq547276542** [comment]
这份代码是TENER代码刚放出来实现的，原作者已经对代码进行过多次修正，可以参考原作者的commit记录
本人已长期无维护该代码，欢迎PR :)

> https://github.com/qq547276542/TF_adapting_transformer/blob/8c28f22f5cd4e81b29e1cbad02257aa96cca7bf3/relative_transformer_module.py#L82
> 
> 
> 对比原作者torch的实现，此处略有不同，请问这么实现是基于什么考虑呢？另外，原作者此处的代码自己也没怎么理解透 :)
